- .gitignore
- docs.py
- docs/index.html
- docs/model.html
- docs/simulation-parameter.html
- honeybee_model_schema/_base.py
- honeybee_model_schema/_openapi.py
- honeybee_model_schema/energy/_base.py
- honeybee_model_schema/energy/schedule.py
This commit adds a separate web page for the energy SimulationParameter schema and a landing page that allows people to select which docs they would like to view.
I also cleaned up some of the descriptions of the schema keys.
@mostaphaRoudsari , as you said, you don't need to review this one but I just wanted you to be aware of this PR since it include the change to making a consistent `_openapi` module that is able to export the schema of any pydantic class that is passed to it.
> feat(docs): Add a separate page for SimulationParameter and landing page

- deploy.sh
- honeybee_schema/_openapi.py
This officially puts the honeybee_schema package on PyPI so that it can be used by other schema repos (like the future dragonfly_schema repo).
> feat(pip): Set up deploment to PyPI

- honeybee_schema/energy/schedule.py
Times should used ints for hours and minutes. Not floats.
> fix(schedule): Fix bug in previous commit

- honeybee_schema/energy/designday.py
It seems that this was the result of some issue with the Pydantic Field class. What I have now fixes it.
> fix(sky_condition): Fix translation of sky_condition to OpenAPI

- honeybee_schema/bc.py
- honeybee_schema/energy/hvac.py
- honeybee_schema/energy/load.py
- honeybee_schema/energy/schedule.py
- honeybee_schema/model.py
- setup.py
This commit allows schema users to store the units system and tolerance with their Model JSONs. The aim of this is that, by specifying these values, schema users don't need to worry about tedious geometry checks like whether all faces point outwards from a Room. This also means that they can build the Models in the units systems that they want and our core libraries will take care of any geometry scaling needed before the export to simulation engines. This should be a relief to Konrad who has to deal with Revit using feet as its native units system.
@mostapharoudsari , the only case that worried me a bit about storing tolerance and units systems on the Model is that I know you have a whole separate schema for point grids and this makes me wonder if the units system should be specified …
> feat(model): Add properties for units and tolerance

- .travis.yml
I think pydantic might not be working correctly in Python 3.6
> fix(ci): Use Python 3.7 for docs generation

- README.md
Since it's now very clear to me that the repo is not compatible with Python 3.6 as a result of the pydantic dependency.
> docs(readme): Increment to Python 3.7

- honeybee_schema/energy/properties.py
Now that it is possible to specify the constructions of ModelEnergyProperties under the construction sets, the keys for constructions and materials should now be optional.
> fix(model): ModelEnergyProperties.constructions are now optional

- honeybee_schema/energy/constructionset.py
- honeybee_schema/energy/hvac.py
- honeybee_schema/energy/load.py
- samples/construction_set/constructionset_abridged_complete.json
- samples/construction_set/constructionset_abridged_partial_exterior.json
- samples/construction_set/constructionset_complete.json
- samples/construction_set/constructionset_partial_exterior.json
- samples/model/model_complete_multi_zone_office.json
- samples/model/model_complete_office_floor.json
- samples/model/model_complete_patient_room.json
- samples/model/model_complete_single_zone_office.json
- samples/model/model_complete_user_data.json
- samples/model/model_energy_detailed_loads.json
- samples/model/model_energy_fixed_interval.json
- samples/model/model_energy_no_program.json
- samples/model/model_energy_properties_office.json
- samples/model/model_energy_shoe_box.json
- tests/test_constructionset.py
This commit changes the class names of sub-sets (eg WallSet) to be specific for energy (eg. WallConstructionSet). This will ensure that the two schemas do not conflict in honeybee-schema.
It also includes a fix for removing an additional layer of AnyOf object hierarchy in the People objects.
> fix(constructionset): Differentiate sub-set class names from radiance

- honeybee_schema/_openapi.py
resolves #86
Current implementation was missing the check for items in an array. Now it is fixed. The new set_format method supports setting up the format for arrays and nested arrays.
> fix(openapi): add format for array items

- .travis.yml
There are inconsistencies between the docs generated for the release and the ones generated for the docs. The only difference is the Python version. Hopefully this change will fix the issue.
> fix(openapi): avoid overwriting description in info

- .github/workflows/emit-release-event.yaml
dependbot takes care of sending a PR to dragonfly-schema
> ci(release event workflow): remove dragonfly-schema

- dev-requirements.txt
- honeybee_schema/radiance/modifier.py
- requirements.txt
- tests/test_openapi_docs.py
This is a change merely to fix the issue for generating the OpenAPI docs with inheritance. From Pydantic point of view the code is good as is but it's not the case for generating the schema with inheritance.
For some mysterious reason the `update_forward_ref` for `_REFERENCE_UNION_MODIFIERS` doesn't get triggered in `ModifierBase` class when creating the subclasses. Moving the fields that are dependent on `_REFERENCE_UNION_MODIFIERS` to the subclasses resolves the issue.
I know that this is adding some code duplication but it fixes the documentation issue for now. I'm willing to spend more time in the near future to find a better fix.
resolves #102
The test for docs will fail with the current bug in Pydantic but as mentioned in #102 it will work fine once the fix for OpenAPI documentation …
> Fix documentation issue

- honeybee_schema/energy/simulation.py
- samples/model/model_5vertex_sub_faces_interior.json
- samples/simulation_parameter/simulation_par_detailed.json
- samples/simulation_parameter/simulation_par_simple.json
- scripts/sample_model.py
The more that I have thought about this, there appear to be more cases where our legacy default of FullInteriorAndExteriorWothReflections doesn't add much accuracy. At the same time, it can really increase simulation time and the risk of severe errors. The interior reflections are overkill for most studies of energy use, thermal loads, and HVAC size. They are also probably overkill for thermal comfort studies using the averaged results over a zone.
> fix(solar): Change default solar distribution to FullExteriorWithReflect

- docs.py
- docs/index.html
- docs/sensor-grid.html
- docs/view.html
- honeybee_schema/radiance/asset.py
This commit will add the SensorGrid and View schemas to the online docs.
I also realized I could cut down the code a bit in the radiance.asset module by using inheritance.
Resolves https://github.com/ladybug-tools/honeybee-schema/issues/135
> docs(assets): Add SensorGrid and View to the online schema docs

- honeybee_schema/energy/simulation.py
I realized it really doesn't add to the simulation time much and it's better to have it there if people want it.
> fix(simulationparameter): Change default to include html

- honeybee_schema/energy/simulation.py
- samples/simulation_parameter/simulation_par_detailed.json
- samples/simulation_parameter/simulation_par_simple.json
- scripts/sample_simulation.py
This commit upgrades the ShadowCalculation schema such that it can work with OpenStudio 3.0 and EnergyPlus 9.3.
@MingboPeng  and @mostaphaRoudsari . I wasn't expecting feedback on the commit but I requested your review since I wanted you to be aware that this seems to be the only schema change that was needed to upgrade to OpenStudio 3.0.
> feat(energy): Upgrade ShadowClaculation schema to use OpenStudio 3.0

- honeybee_schema/model.py
I think I'm already learning the hard way that, if there are checks that need to be performed in order to ensure a model simulates correctly, then the default should not be to bypass these checks.
Along these lines, I am setting the default Model tolerances to be a positive number (albeit a somewhat arbitrary one that's kinda meters-centric) just so I don't end up with cases of models not simulating because a user didn't bother to set the tolerance to something that made sense.
@MingboPeng  and @mostaphaRoudsari . I only requested your review here so that you are aware of this decision.
> fix(tolerance): Do not make bypassing checks the default

- honeybee_schema/energy/construction.py
This is a bug in the schema that I did not realize until I noticed that EnergyPlus will not simulate if there is a shade/blind layer in a window construction.
It feels like a dumb idiosyncrasy as E+ clearly has the ability to simulate a static shade or blind in a construction but it's just fussy if it doesn't get the blind or shade in the format it wants.
So it seems that I will have to create a new type of construction object (`ShadedWindowConstruction`) that will allow the assignment of shades to `WindowConstructions` and give EnergyPlus what it wants. This will be in the next PR that I send and I am just trying to prevent people from making un-simulate-able models with this PR.
@MingboPeng . I just wanted you to be aware of this change so you can update the DotNet side of things and …
> fix(construction): Shade materials are not useable in WindowConstruction

- honeybee_schema/energy/construction.py
- honeybee_schema/energy/properties.py
- samples/construction/construction_window_shade.json
- scripts/sample_construction.py
- tests/test_construction.py
This PR is coordianted with [this one over on honeybee-energy](https://github.com/ladybug-tools/honeybee-energy/pull/211).  
It fixes the way that blinds and shades were represented in the schema previously, which could never be simulated by EnergyPlus since E+ always needs a ShadingControl object in order to be able to simulate them. So I added a new WindowConstructionShaded class to handle the creation of this ShadingControl object and allow users to change some of its properties.
@MingboPeng , I just requested you review here so that you are aware of the change.
> feat(construction): Add WindowConstructionShade schema

- .travis.yml
The prepareCmd script in .releaserc.json already generates versioned docs so we re-use them when
deploying to GH pages.
close #161
> ci(docs): use versioned docs generated by semantic-release

- honeybee_schema/energy/properties.py
- honeybee_schema/energy/ventcool.py
- samples/model/model_energy_window_ventilation.json
- samples/ventcool/ventilation_control_detailed.json
- samples/ventcool/ventilation_control_simple.json
- samples/ventcool/ventilation_opening_default.json
- scripts/sample_hvac.py
- scripts/sample_model.py
- scripts/sample_ventcool.py
- tests/test_model.py
- tests/test_ventcool.py
This commit adds objects for simple window-based ventilative cooling. While this commit only includes enough objects to model windows with ZoneVentilation:WindandStackOpenArea objects, many of these objects should also be used in the future AFN.
@mostaphaRoudsari , if you get the chance, please let me know if you have any comments on the vocabulary / terminology that I'm using here for the objects.
@saeranv , feel free to ask any questions that relate to your work as review comments.
> feat(ventcool): Add objects for simple window-based ventilative cooling

- .travis.yml
The current build for docs was failing since the line for installing redoc-cli has been removed here: https://github.com/ladybug-tools/honeybee-schema/commit/37b84fff45b5d0ab6666df8e1f81c03607a5234e
> ci(travis): put redoc-cli back

- honeybee_schema/radiance/wea.py
I also added a check to ensure that the lengths of the two irradiance lists match and that datetimes are provided whenever the length of these lists is not annual.
I'm just letting you know about the update, @mostaphaRoudsari , and everything I'm adding here is in accordance with the PR you just reviewed.
> fix(wea): Update Wea schema to include datetimes

- honeybee_schema/energy/designday.py
- honeybee_schema/energy/hvac/_template.py
- honeybee_schema/energy/hvac/allair.py
- honeybee_schema/energy/hvac/doas.py
- honeybee_schema/energy/hvac/heatcool.py
- honeybee_schema/energy/hvac/idealair.py
- honeybee_schema/energy/material.py
- honeybee_schema/energy/properties.py
- honeybee_schema/energy/simulation.py
- samples/hvac/fcu_with_doas_template.json
- samples/hvac/vav_template.json
- samples/hvac/window_ac_with_baseboard_template.json
- samples/model/model_energy_allair_hvac.json
- samples/model/model_energy_doas_hvac.json
- samples/model/model_energy_window_ac.json
- scripts/sample_hvac.py
- scripts/sample_model.py
- tests/test_hvac.py
- tests/test_model.py
This commit adds modules and classes for the ~120 HVAC templates that are available in the OpenStudio standards gem.
@MingboPeng  and @mostaphaRoudsari , please let me know any comments that you have.
I'll be adding some samples and tests soon but, right now, it's just the pure pydantic stuff.
> feat(hvac): Add classes for detailed HVAC templates

- honeybee_schema/energy/ventcool.py
- samples/model/model_energy_window_ventilation.json
- samples/ventcool/ventilation_opening_default.json
If we want to use the discharge coefficient in both simple ventilation and the AFN, it seems we should follow the E+ guide and use a coefficient that corresponds to the height from midpoint of lower opening to the neutral pressure level (deltaHnpl) instead of using the full height of the window.
> fix(ventcool): Set default discharge coefficient to 0.45 for deltaHnpl

- honeybee_schema/energy/properties.py
- honeybee_schema/energy/ventcool.py
- samples/model/model_energy_afn.json
- samples/model/model_energy_window_ventilation.json
- samples/ventcool/ventilation_crack.json
- samples/ventcool/ventilation_simulation_control.json
- scripts/sample_model.py
- scripts/sample_ventcool.py
- tests/test_model.py
- tests/test_ventcool.py
@chriswmackey, 
cc @mostaphaRoudsari 
This is the first draft of the AFN objects we are adding to the VentCool module, in the Honeybee Schema. Once I implement the AFN objects in honeybee-energy, I'll create some test jsons, and add unit tests to this PR. 
Note that the EnergyPlus implementation will require EMS objects (i.e. EMS:Sensor, EMS:Actuator, EMS:ProgramCallingManager, and the EMS:Program), to coordinate these AFN objects with the VentControl in Honeybee. None of these EMS objects are referenced in the schema since it'll just be referencing existing objects and doesn't need to be modified by the user.
Also, you'll notice that in the AFNSimulationControl object, there's a number of fields requiring the geometric properties of a building footprint that is roughly rectangular. Since …
> feat(ventcool): Add AFN objects to VentCool.

- honeybee_schema/energy/load.py
This new property will provide a user interface for setting the lighting power density in the baseline model creation workflows. This property is really only relevant when users are creating their own ProgramTypes from scratch (as opposed to using the ProgramTypes that come with the honeybee-energy-standards package).
The plan is that the baseline model creation workflows will first look for an equivalent ProgramType in the ASHRAE-2004 standard and use the LPD there. If an equivalent ProgramType in 2004 is not found, this baseline_watts_per_area property will be used instead. The default value for this property is the ASHRAE 2004 baseline for an office, which is the recommended approach when a given program cannot be classified into any of the categories of the ASHRAE standard. …
> fix(lighting): Add baseline_watts_per_area to Lighting class

- requirements.txt
There's no need for the pydantic dependency here now that it is included within pydantic-openapi-helper==0.1.6
> style(requirements): Ensure dependencies are listed only once

- .github/workflows/ci.yaml
- .releaserc.json
- docs.py
1. fix path to docs folder
2. added JSON Schema object for honeybee model. resolves #182
I also tried to generate a new file without discriminator to fix the docs. It makes it slightly better but doesn't fix the issue. Related #221
> ci(docs): fix docs deployment

- honeybee_schema/radiance/asset.py
I am also putting back the older behavior of the SensorGrid and View identifiers. So identifiers are now used to specify the filenames in the model folder (instead of the display_name).
CC: @mostaphaRoudsari , @devngc
> fix(sensorgrid): Add base_geometry property for SensorGrid

- honeybee_schema/cli.py
- tests/test_cli.py
This commit takes advantage of python's inspect and pkgutil and removes `eval`s from the code.
I also added some reporting and updated the test. Click.runner has a bug and mixes the stderr and stdout which was making the test fail after these changes.
> refactor(updater): refactor updater and removed use of eval

- honeybee_schema/energy/load.py
- honeybee_schema/energy/properties.py
- samples/daylight/daylight_control.json
- tests/test_daylight_control.py
@mingbopeng , This change is purely optional and additive to the schema so there's no need to make any change to the packages using the C# bindings. You can feel free to expose it whenever you get the time and there's no pressure. I only added it as SOM asked to test it during the URBANopt pilot testing period.
The only potentially thing to think through when you eventually expose it is that the daylight controls need a sensor point. So you may need to ask the user for a point that's inside the room volume.
> feat(load): Add an object for EnergyPlus DaylightControl

- honeybee_schema/energy/construction.py
- samples/construction/construction_opaque_door.json
- samples/construction/construction_opaque_roof.json
- samples/construction/construction_opaque_wall.json
- samples/construction/construction_window_blinds.json
- samples/construction/construction_window_double.json
- samples/construction/construction_window_shade.json
- samples/construction/construction_window_triple.json
- samples/construction_set/constructionset_complete.json
- samples/construction_set/constructionset_partial_exterior.json
- samples/model/model_complete_multi_zone_office.hbjson
- samples/model/model_complete_single_zone_office.hbjson
- samples/model/model_energy_no_program.hbjson
- samples/model/model_energy_shoe_box.hbjson
- samples/model_large/lab_building.hbjson
- samples/model_large/single_family_home.hbjson
- tests/test_construction.py
This commit changes the construction schema to work like all other abridged/non-abridged schemas. The materials key just contains identifiers when abridged and fully-detailed materials when not abridged.
Resolves https://github.com/ladybug-tools/honeybee-schema/issues/271
CC: @mingbopeng , @AntonelloDN
> fix(construction): Change construction schema to be more consistent

- .dependabot/config.yml
- dev-requirements.txt
- setup.py
I am also rolling back the click version of the [cli] extra so that we don't end up with version conflicts with the rest of the core libraries.
> ci(deps): Prevent auto-updating dependencies

- honeybee_schema/energy/material.py
- tests/test_material.py
This includes:
* Lifting the restriction of 5.8 as the max U-value
* Fixing 2 cases of default=None used for optional floats
* Fixing the descriptions to be consistent with the rest of the repo
> fix(material): Make several fixes to energy material module

- honeybee_schema/model.py
- honeybee_schema/radiance/asset.py
I realized that we should permit the . for all of the relevant regexes.
> fix(regex): Ensure that regexes are consistent

- honeybee_schema/energy/constructionset.py
- honeybee_schema/energy/global_constructionset.py
- honeybee_schema/energy/properties.py
- honeybee_schema/radiance/global_modifierset.py
- honeybee_schema/radiance/properties.py
- requirements.txt
Instead of having the "source of truth" for default constructions and modifiers living in an external JSON file in `honeybee_standards`, this commit adds this "source of truth" into honeybee-schema and effectively has it recorded/copied each HBJSON Model.
This way, when other developers receive a HBJSON model, they won't need to have a copy of `honeybee_standards` but can instead just read the `global_modifier_set` and `global_construction_set` properties from the Model JSON itself. These global sets are read-only and will effectively be static for a given version of honeybee-schema.
> feat(global): Add global construction and modifier sets

- honeybee_schema/radiance/global_modifierset.py
- honeybee_schema/radiance/modifier.py
- requirements.txt
- tests/test_modifier.py
This is linked to this issue here:
https://discourse.ladybug.tools/t/airboundary-not-considered-fully-transparent-by-radiance/15191/
> fix(global_modifierset): Ensure air boundaries use invisible trans

- honeybee_schema/energy/_base.py
- honeybee_schema/energy/schedule.py
- honeybee_schema/radiance/modifier.py
This brings the schema to be in line with the latest honeybee-energy library, which supports user_data for things like constructions.
I am also changing the Glass.refraction_index to be greater than 1 since it seems that values less than 1 will cause Radiance to get stuck in an endless loop.
> fix(energy): Add user_data key to all energy resource objects

- honeybee_schema/energy/simulation.py
- samples/simulation_parameter/simulation_par_detailed.json
- samples/simulation_parameter/simulation_par_simple.json
@mingbopeng , I originally put these properties into the simulation parameters since I was not sure if they would be exposed on the OpenStudio SDK at some point. Now that I have confirmation that NREL does not intend to expose them since they could could break reporting measures, I think they should be removed from honeybee-schema. I'm requesting your review here before I merge so that you get a chance to fix things on the Rhino plugin before these properties are gone. Please feel free to merge this PR as soon as you are ready for he change, @mingbopeng .
> fix(simulation): Remove non-functional properties of energy sim param

- honeybee_schema/energy/hvac/_template.py
- honeybee_schema/energy/hvac/doas.py
- honeybee_schema/energy/hvac/heatcool.py
- honeybee_schema/energy/properties.py
- honeybee_schema/model.py
Resolves https://github.com/ladybug-tools/honeybee-energy/issues/526
Resolves https://github.com/ladybug-tools/honeybee-openstudio-gem/issues/184
> feat(hvac): Add templates for radiant HVAC

- requirements.txt
This is creating all kinds of headaches with the other repos, especially those like the VTK ones that only use pydantic and not the openapi helper.
> fix(deps): Loosen pydantic requirement

- honeybee_schema/validation.py
> fix(validation): Tweak ValidationError to work for multiple objects

- docs.py
- honeybee_schema/energy/simulation.py
- honeybee_schema/project_info.py
Here is the first draft based on the discussions on Basecamp.
> feat(project info): add schema for project information
