ladybug-tools/honeybee-schema

README.md, honeybee_model_schema/_base.py, honeybee_model_schema/bc.py, honeybee_model_schema/datetime.py, honeybee_model_schema/energy/_base.py, honeybee_model_schema/energy/construction.py, honeybee_model_schema/energy/constructionset.py, honeybee_model_schema/energy/designday.py, honeybee_model_schema/energy/hvac.py, honeybee_model_schema/energy/load.py, honeybee_model_schema/energy/material.py, honeybee_model_schema/energy/programtype.py, honeybee_model_schema/energy/properties.py, honeybee_model_schema/energy/schedule.py, honeybee_model_schema/energy/simulation.py, honeybee_model_schema/model.py, honeybee_model_schema/samples/lighting_abridged.json, requirements.txt, tests/test_load.py
This commit upgrades this repo to use pydantic 1.3. This also includes the switching over of several validators to be root_validators and adds a few root_validators in places where they really should exist.
=> feat(pydantic): Upgrade to pydantic 1.3

.travis.yml, honeybee_model_schema/bc.py, honeybee_model_schema/datetime.py, honeybee_model_schema/energy/construction.py, honeybee_model_schema/energy/constructionset.py, honeybee_model_schema/energy/designday.py, honeybee_model_schema/energy/hvac.py, honeybee_model_schema/energy/load.py, honeybee_model_schema/energy/material.py, honeybee_model_schema/energy/programtype.py, honeybee_model_schema/energy/properties.py, honeybee_model_schema/energy/schedule.py, honeybee_model_schema/energy/simulation.py, honeybee_model_schema/model.py
This is shorter to write and means than when serialized to terminal/file workflow class instances.
=> fix(pydantic): replace enum values with regex validation

honeybee_schema/energy/schedule.py, honeybee_schema/energy/simulation.py, honeybee_schema/model.py
I had been using validators to check that the length of embedded lists were correct but I just realized that conlist can do the same thing but better.
=> feat(conlist): Implement more elegant way to constrain list length

honeybee_schema/model.py
This commit brings the library in line with [this PR on honeybee-core](https://github.com/ladybug-tools/honeybee-core/pull/52).
=> feat(door): Allow Shades to be assigned to Doors

requirements.txt
This should fix an issue with the recent patch that I added.
=> fix(pydantic): Upgrade to Pydantic 1.4

.github/workflows/emit-release-event.yaml, .releaserc.json, docs.py, honeybee_schema/_openapi.py
I had to make a couple of changes to the `docs.py` script to let it take an optional `--version` argument which will be used when creating the new release.
=> Release automation

honeybee_schema/energy/construction.py, honeybee_schema/energy/constructionset.py, honeybee_schema/energy/load.py, honeybee_schema/energy/programtype.py, honeybee_schema/energy/schedule.py
Updated ScheduleRuleset, ScheduleFixedInterval, AirBoundaryConstruction, ConstructionSet, ProgramType with detailed schemas, as well as dependant schemas required. 
@chriswmackey this is ready for review. I took a stab at defining the fields for the various detailed schemas as best as I could based on understanding of pydantic, but I there might be omissions.
=> feat(honeybee_schema): Detailed equivalents for abridged  schemas.

honeybee_schema/energy/properties.py
I'm also sending this PR in the hopes that it will trigger the openAPI schema to regenerate correctly.
=> feat(docs): Improving descriptions of ModelEnergyProerties

honeybee_schema/energy/simulation.py
Things keep failing in our deployment process because various web services are down. I'm sending this commit in an attempt to trigger another build.
=> feat(docs): Try to trigger build again

honeybee_schema/energy/constructionset.py
This commit makes the ConstructionSet schema more easily deconstructable/editable.
=> feat(constructionset): Refactor ConstructionSet schema

.releaserc.json, docs.py, honeybee_schema/_openapi.py
1. make inheritance recursive and only for extended objects
2. add a mapper file to map each object to its python module
3. add newly generated files to assets so it can be downloaded for each release
=> improve openapi docs

docs.py, honeybee_schema/_openapi.py
=> refactor(openapi): make get_openapi function reusable

.travis.yml
Currently the older version of the docs is included in each release.
@mingboPeng, this should resolve the issue for you.
=> fix(docs): generated docs before release

docs.py
@MingboPeng, this should resolve the issue with the version.
=> fix(openapi): version must be a number not a tuple

honeybee_schema/model.py, honeybee_schema/radiance/modifier.py, honeybee_schema/radiance/modifierset.py, honeybee_schema/radiance/properties.py
@chriswmackey @mostaphaRoudsari
This PR is ready for review.
=> feat(Model, Modifier): Add properties to model.py and mirror to modifier.py

samples/model/model_5vertex_sub_faces.json, scripts/sample_model.py, tests/test_model.py
Given that this is only adding a sample file, I hope everyone is ok with me merging this in without review. I just needed this sample file to help with testing of the energy-model-measure and I would rather that the samples here not get out of sync with the samples we use for testing over on the measure.
=> docs(samples): Add a sample with more than 4 vertices for sub-faces

honeybee_schema/_openapi.py
resolves #101
Note that it will not fix the online documentation because of #102
=> fix(openapi): remove duplicate properties field

.gitignore, .travis.yml, setup.py
Added a temporary fix to handle links from github in setup.py.
=> fix(setup.py): handle links to git

honeybee_schema/radiance/modifier.py
=> fix(rad-modifier): set default modifier to Optional Void

samples/model/model_radiance_dynamic_states.json, samples/state/aperture_state_abridged_shades.json, samples/state/shade_state_abridged_tree_foliage.json, scripts/sample_model.py, scripts/sample_state.py
This is related to [this PR over on honeybee-radiance](https://github.com/ladybug-tools/honeybee-radiance/pull/93). It updates the sample model JSON and state JSONs that @saeranv should use in his testing.
Since this is a docs-only PR, I am going to merge it in without review but I've added Mostapha and Saeran as reviewers so that they are aware of the change.
=> docs(samples): Update Sample with dynamic radiance objects

.travis.yml
=> ci(travis.yml): generate static html using redoc-cli

honeybee_schema/geometry.py, honeybee_schema/model.py, honeybee_schema/radiance/_base.py, honeybee_schema/radiance/modifier.py, honeybee_schema/radiance/properties.py, honeybee_schema/radiance/state.py, tests/test_state.py
@mostaphaRoudsari @chriswmackey 
I think the last PR for the Schema States was accidently force-pushed, even though we hadn't finished all the changes. This PR addresses all the previous comments, with working unit tests.
=> Revise State schema

docs.py, honeybee_schema/_openapi.py
re: https://github.com/ladybug-tools/dragonfly-schema/issues/63
@MingboPeng, here are the file generated for honeybee-schema. Let me know if  the files look good to you and I can send a PR to dragonfly and close the issue.
[openapi_spec.zip](https://github.com/ladybug-tools/honeybee-schema/files/4612950/openapi_spec.zip)
=> perf(openapi): make enum objects reusable

honeybee_schema/radiance/asset.py
This updates the schema to be aligned with this change here:
https://github.com/ladybug-tools/honeybee-radiance/pull/101
@mostaphaRoudsari , this is in-line with our discussions on the honeybee-radiance PR so I am going to merge it in. I just wanted you to be aware of the change and just let me know if this is not what you were expecting.
=> feat(light_path): Add light_path property for SensorGrid and View

honeybee_schema/_openapi.py
currently the code was only changing the enum object for its first occurrence. It is now fixed.
resolves #138
=> fix(openapi-spec): add duplicate enums

honeybee_schema/energy/construction.py
Resolves https://github.com/ladybug-tools/honeybee-schema/issues/155
=> fix(construction): Remove schema_extra from WindowConstructionShade

docs.py
I also fixed a PEP8 indentation issue.
=> ci(docs): Include schema version in Model.version default

samples/model/model_energy_afn.json, scripts/sample_model.py
@chriswmackey 
This PR adds exterior window, more detailed ventilation opening, and simulation control to the model_energy_afn.json sample and script.
=> fix(afn): Correct bugs in afn properties for model_energy_afn.json.

.releaserc.json, .travis.yml
=> fix(release asset): make the names consistent

README.md, dev-requirements.txt
I am also trying to add a hard-coded importlib-metadata requirement to ensure that PyPI deployment happens correctly.
=> docs(readme): Update readme

honeybee_schema/energy/hvac/allair.py
See more here:
https://discourse.ladybug.tools/t/hvac-doas-templates/12002/11
=> fix(hvac): Remove unnecessary PSZ template

.github/workflows/ci.yaml, honeybee_schema/energy/load.py, honeybee_schema/energy/programtype.py, honeybee_schema/energy/properties.py, samples/model/model_energy_service_hot_water.hbjson, samples/program_type/program_type_office.json, scripts/sample_model.py, scripts/sample_program_type.py, tests/test_model.py
This is coordinated with this PR:
https://github.com/ladybug-tools/honeybee-energy/pull/497
CC: @mingbopeng , @mostapharoudsari
This should not break any older workflows since service hot water is completely optional.
=> feat(load): Add ServiceHotWater to Program and Room

.github/workflows/ci.yaml
=> fix(ci): fix docs version

.github/workflows/ci.yaml, docs.py, honeybee_schema/radiance/asset.py
Hey @chriswmackey, we have already discussed adding group identifier to sensor grids and views but let me know if you think I should change anything in this PR.
=> feat: add group identifier to SensorGrid and View

honeybee_schema/energy/construction.py
Resolves https://github.com/ladybug-tools/honeybee-schema/issues/269
=> docs(construction): Fix incorrect description of construction materials

honeybee_schema/energy/daylight.py, honeybee_schema/energy/hvac/allair.py, honeybee_schema/energy/hvac/doas.py, honeybee_schema/energy/load.py, honeybee_schema/energy/properties.py, honeybee_schema/updater/version_1_43_1.py, samples/hvac/fcu_with_doas_template.json, samples/model/model_energy_doas_hvac.hbjson, tests/test_daylight_control.py, tests/test_hvac.py
I am also adding an option to include a humidifier, which is needed for all cases where there's a humidification setpoint.
This is linked to this change:
https://github.com/ladybug-tools/honeybee-energy/pull/669
FYI @mingbopeng . This is technically a breaking change and you'll see that I added a method to the updater module to upgrade old model JSONs. However, this should hopefully not require much change on your end except exposing the new properties. And I implemented the changes in the Python libraries in such a manner that older Honeybee JSONs can still be imported by the latest libraries.
=> fix(hvac): Add option for demand controlled ventilation

honeybee_schema/updater/version_1_43_2.py
I forgot to add this with the last PR.
=> fix(updater): Add function to update constructions

honeybee_schema/energy/constructionset.py
Thanks for catching this one @tanushree04 !
=> docs(constructionset): Fix incorrect description

scripts/sample_model_large.py
It seems the identifiers were not perfectly unique.
=> docs(samples): Small fix to urban_district.hbjson

honeybee_schema/model.py
This is coordinated with this issue:
https://github.com/ladybug-tools/honeybee-core/issues/509
=> fix(room): Add exclude_floor_area property to Room

honeybee_schema/energy/hvac/allair.py, honeybee_schema/energy/hvac/doas.py, honeybee_schema/energy/hvac/heatcool.py
@MingboPeng ,
Let me know if you'll be able to use these descriptions in the Rhino plugin given that I just added them to the docstrings of the classes.
=> fix(hvac): Include better descriptions of HVAC templates

honeybee_schema/energy/hvac/allair.py, honeybee_schema/energy/simulation.py
This will enable people to match a particular version of ASHRAE 90.1 exactly.
It also includes a bug fix and a few edits to the HVAC templates in order to fully support SAHRAE 90.1.
=> feat(simulation): Add properties to specify efficiency standard

.github/workflows/ci.yaml, honeybee_schema/doe2/properties.py, honeybee_schema/model.py
I don't think we necessarily need to expose these properties on the UI yet but, if people assign them, I do not want them to be lost as we send HBJSONs between different bindings.
=> feat(doe2): Document newly added properties for DOE-2
